apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-ml-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/articlesmli/enterprise_ml_studio.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
