apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.11.3
        ports:
        - containerPort: 5000
        command:
          - /bin/sh
          - -c
          - |
            pip install --no-cache-dir psycopg2-binary &&
            exec mlflow server \
              --host 0.0.0.0 \
              --port 5000 \
              --backend-store-uri postgresql://ml_user:ml_password@ml-postgres:5432/ml_studio \
              --default-artifact-root mlflow-artifacts:/ \
              --artifacts-destination /mlflow/artifacts \
              --serve-artifacts
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow/artifacts
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-artifact-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-server
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000