name: Enterprise ML CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pyspark pandas psycopg2-binary

      - name: Run Code Linting
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build-and-push:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/enterprise_ml_studio:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Authenticate to Cluster
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      # - name: Apply Kubernetes Manifests
      #   run: |
      #     kubectl apply -f k8s-full-stack.yaml
      #     kubectl rollout restart deployment/enterprise-ml-deployment

      - name: Restart Kubernetes Deployments and Jobs
        run: |
          kubectl rollout restart deployment/enterprise-ml-deployment
          kubectl rollout restart job/enterprise-ml-spark-job